# Generated by Django 4.1.1 on 2022-10-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_app', '0007_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.CharField(max_length=50, null=True)),
                ('catagory', models.CharField(choices=[('DOCUMENT-COLLECTION', 'DOCUMENT-COLLECTION'), ('DOCUMENTATION', 'DOCUMENTATION'), ('CLIENT-MEETING', 'CLIENT-MEETING')], default='DOCUMENTATION', max_length=50, null=True, verbose_name='Status')),
                ('date', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'PROJECT_NOTES',
                'verbose_name_plural': 'PROJECT_NOTES',
                'db_table': 'PROJECT_NOTES',
            },
        ),
    ]
