# Generated by Django 4.1.1 on 2022-10-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_app', '0008_projectnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectnotes',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
